=== PeterisP/cards-against-humanity/src/main/data/schema/dictionary.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT dictionary (entry*) >

<!ELEMENT entry (term+) >

<!ELEMENT term (#PCDATA)>
<!ATTLIST term
    xml:lang NMTOKEN #REQUIRED >

=== PeterisP/cards-against-humanity/src/main/data/dictionaries/english.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dictionary PUBLIC "-//Kaikoda//DTD CAH Dictionary 1.0//EN" "../schema/dictionary.dtd">
<dictionary>
	<entry>
		<term xml:lang="en-us">TSA</term>
		<term xml:lang="en-gb">UK Border Agency</term>
		<term xml:lang="en-nl">Royal Marechaussee</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Judge Judy</term>
		<term xml:lang="en-gb">Jeremy Kyle</term>
		<term xml:lang="en-nl">The Driving Judge</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Hardworking Mexican</term>
		<term xml:lang="en-gb">Hardworking Poles</term>
	</entry>
	<entry>
		<term xml:lang="en-us">The Kool-Aid Man</term>
		<term xml:lang="en-gb">Captain Birds Eye</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Switching to Geico™</term>
		<term xml:lang="en-gb">ComparetheMeerkat.com</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Adderall™</term>
		<term xml:lang="en-gb">Ritalin™</term>
	</entry>
	<entry>
		<term xml:lang="en-us">John Wilkes Booth</term>
		<term xml:lang="en-gb">Guy Fawkes</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Racially-biased SAT questions</term>
		<term xml:lang="en-gb">Unfairly marked GCSEs</term>
	</entry>
	<entry>
		<term xml:lang="en-us">A Bop It™</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Fancy Feast™</term>
		<term xml:lang="en-gb">Pedigree Chum™</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Aaron Burr</term>
		<term xml:lang="en-gb">Sir Robert Walpole</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Republicans</term>
		<term xml:lang="en-gb">Tories</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Rush Limbaugh's soft, shitty body</term>
		<term xml:lang="en-gb">Melanie Phillips wanking herself into a franzy while wanging on about Israel</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Filling Sean Hannity with helium and watching him float away</term>
		<term xml:lang="en-gb">Serving Michael Winner soup with &quot;chef's special sauce&quot;</term>
	</entry>
	<entry>
		<term xml:lang="en-us">GoGurt™</term>
		<term xml:lang="en-gb">Frubes™</term>
		<term xml:lang="en-nl">Breaker™</term>
	</entry>
	<entry>
		<term xml:lang="en-us">All-you-can-eat shrimp for $4.99</term>
		<term xml:lang="en-gb">A deep fried Mars™ bar</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Hot Pockets™</term>
		<term xml:lang="en-gb">A Cornish Pasty™</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Five-Dollar Footlongs™</term>
		<term xml:lang="en-gb">British Rail BLT</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Pabst Blue Ribbon™</term>
		<term xml:lang="en-gb">Stella Artois™</term>
	</entry>
	<entry>
		<term xml:lang="en-us">Major League Baseball</term>
		<term xml:lang="en-gb">Premier League Football</term>
		<term xml:lang="en-nl">The Premier Division</term>
	</entry>
</dictionary>
